application: ebcmdev
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /themes
  static_dir: templates/themes

- url: /twilio
  static_dir: twilio

- url: /httplib2
  static_dir: httplib2

- url: /venv
  static_dir: venv

- url: /static
  static_dir: static

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: knoknok.py

skip_files:
- ^(.*/)(dev).py
