application: ebcmdev
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: ../templates/themes
  static_dir: ../Knoknok/templates/themes

- url: ../themes
  static_dir: ../Knoknok/templates/themes

- url: ../static
  static_dir: ../Knoknok/static

- url: ../stylesheets
  static_dir: ../Knoknok/stylesheets

- url: /.*
  script: knoknok.py

skip_files:
- ^(.*/)(dev).py
