application: getknoknok
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /images
  static_dir: images

- url: /static
  static_dir: static

- url: /.*
  script: getknoknok.py

libraries:
- name: webapp2
  version: "2.5.2"
